name: 'sales_pipelines'
version: '1.0.0'
config-version: 2

profile: 'sales_pipelines'

model-path: ['models']
test-path: ['tests']
macro-path: ['macros']

target-path: 'target'
clean-targets: ['target', 'dbt_packages']

models:
  sales_pipelines:
    staging:
      +schema: staging
      materialized: incremental
    
    processed:
      +schema: processed
      materialized: incremental